version: '3.8'

services:
  footyapp-dev:
    env_file: /app/tokens/.env
    image: ghcr.io/bignellrp/footyapp-api:main
    container_name: footyapp-api-${BRANCH}
    networks:
      br0:
        ipv4_address: 192.168.0.232
    ports:
      - "8080:80"
    volumes:
      - /mnt/user/share/docker/footyapp-api/tokens/:/tokens
    depends_on:
      - mongodb

  mongodb:
    env_file: .env
    image: mongo:latest
    networks:
      br0:
        ipv4_address: 192.168.0.231
    ports:
      - "27017:27017"
    volumes:
      - /mnt/user/share/docker/footyapp-api/mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

volumes:
  mongodb_data:

networks:
  br0:
    external: true
    name: br0