version: '3.8'

services:
  footyapp-api:
    image: ghcr.io/bignellrp/footyapp-api:${BRANCH}
    container_name: footyapp-api-${BRANCH}
    networks:
      - br1
    ports:
      - "2${PORT}:80"
    restart: always
    env_file:
      - /mnt/docker/footyapp-api-${BRANCH}/.env
    environment:
      - TZ=Europe/London
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: footyapp-db-${BRANCH}
    networks:
      - br1
    ports:
      - "27${PORT}:27017"
    restart: always
    env_file:
      - /mnt/docker/footyapp-api-${BRANCH}/.env
    volumes:
      - /mnt/user/share/docker/footyapp-api-${BRANCH}/mongodb_data:/data/db
      - /mnt/user/share/docker/footyapp-api-${BRANCH}/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - TZ=Europe/London

networks:
  br1:
    external: true
    name: br1