version: '3.8'

services:
  footyapp-api:
    image: ghcr.io/bignellrp/footyapp-api:dev
    container_name: footyapp-api-${BRANCH}
    networks:
      br0:
        ipv4_address: 192.168.0.242
    ports:
      - "80:80"
    restart: always
    env_file:
      - /mnt/docker/footyapp-api-dev/.env
    environment:
      - TZ=Europe/London
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: footyapp-db-${BRANCH}
    networks:
      br0:
        ipv4_address: 192.168.0.241
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - /mnt/docker/footyapp-api-dev/.env
    volumes:
      - /mnt/user/share/docker/footyapp-api-dev/mongodb_data:/data/db
      - /mnt/user/share/docker/footyapp-api-dev/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - TZ=Europe/London

networks:
  br0:
    external: true
    name: br0