version: '3.8'

services:
  footyapp-dev:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    env_file: .env
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: